# Generated by Django 3.1.4 on 2020-12-10 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occassion',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='occassion_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.occassion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='relationship_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.relationship'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'female'), ('b', 'both')], max_length=50, null=True),
        ),
    ]
